# language: emacs-lisp
language: ruby

os:
  - linux
  - osx

env:
  matrix:
    - EMACS=emacs24.3
    - EMACS=emacs24.4
    - EMACS=emacs24.5
    - EMACS=emacs-snapshot

sudo: true

addons:
  apt:
    packages:
    - tree
    - wget
    - libxpm-dev
    - libjpeg-dev
    - libgif-dev
    - libtiff4-dev

matrix:
  allow_failures:
    - env:
        - EMACS=emacs-snapshot

install:
  - if [ "$EMACS" = "emacs24.3" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.3.tar.gz &&
        tar -xf emacs-24.3.tar.gz && cd emacs-24.3 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs24.4" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.gz &&
        tar -xf emacs-24.4.tar.gz && cd emacs-24.4 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs24.5" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz &&
        tar -xf emacs-24.5.tar.gz && cd emacs-24.5 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el;
    fi

before_script:
  - echo "build-no: ${TRAVIS_BUILD_NUMBER}\nrepo: ${TRAVIS_REPO_SLUG}\nbranch: ${TRAVIS_BRANCH}\ncommit: ${TRAVIS_COMMIT}\npull-request: ${TRAVIS_PULL_REQUEST}"
  - tree -h

script:
  lsb_release -a && cd /home/travis/build/luismayta/emacs.d && EMACS=emacs ./script/test

after_script:
  - [ -r ~/.emacs.d ] && echo  "\e[32m[✔]\e[0m Yeah .emacs"

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
