# language: emacs-lisp
language: ruby

env:
  matrix:
    - EMACS=emacs24.4
    - EMACS=emacs24.5
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env:
        - EMACS=emacs-snapshot

install:
  - sudo apt-get install wget
  - sudo apt-get install build-essential
  - if [ "$EMACS" = "emacs24.4" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.gz &&
        tar -xf emacs-24.4.tar.gz && cd emacs-24.4 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs24.5" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz &&
        tar -xf emacs-24.5.tar.gz && cd emacs-24.5 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el;
    fi

script:
  lsb_release -a && EMACS=$EMACS ./script/test

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
