language: c

os:
  - linux
  - osx

env:
  matrix:
    - EMACS=emacs24.3
    - EMACS=emacs24.4
    - EMACS=emacs24.5

sudo: true

matrix:
  allow_failures:
    - env:
      - EMACS=emacs-snapshot

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq &&
      sudo apt-get install -y tree &&
      sudo apt-get install -y wget &&
      sudo apt-get install -y libxpm-dev &&
      sudo apt-get install -y libjpeg-dev &&
      sudo apt-get install -y libgif-dev &&
      sudo apt-get install -y libtiff4-dev;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install tree;
    fi

install:
  - if [ "$EMACS" = "emacs24.3" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.3.tar.gz &&
        tar -xf emacs-24.3.tar.gz && cd emacs-24.3 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs24.4" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.gz &&
        tar -xf emacs-24.4.tar.gz && cd emacs-24.4 &&
        ./configure &&
        make &&
        sudo make install;
    fi
  - if [ "$EMACS" = "emacs24.5" ]; then
        wget http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz &&
        tar -xf emacs-24.5.tar.gz && cd emacs-24.5 &&
        ./configure &&
        make &&
        sudo make install;
    fi

script:
  uname -a && EMACS=emacs ./script/test

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
