# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up

version: '3'
services:
  app:
    restart: always
    environment: &environment
      - APP_NAME=emacs
    volumes:
    - ./:/home/.emacs.d
    env_file:
      - .env

  docs:
    restart: always
    volumes:
      - .:/usr/src
    env_file:
      - .env
