# emacs: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:
  emacs:
    restart: always
    image: luismayta/ubuntu-emacs:emacs24.5
    build:
      context: .
      dockerfiles: docker/emacs/Dockerfile
    volumes:
    - ./:/home/.emacs.d
