# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3"
services:

  app:
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    environment: &environment
      - APP_NAME=emacs
      - STAGE=local
    volumes:
    - ./:/home/.emacs.d
    env_file:
      - .env

  docs:
    restart: always
    volumes:
      - .:/usr/src
    env_file:
      - .env
