# emacs: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:
  app:
    image: luismayta/ubuntu-emacs:emacs24.5
    build:
      context: .
      dockerfiles: docker/emacs/Dockerfile
