@startuml
autonumber
emacs -> init.el : package-refresh-content
emacs -> init.el : settings paths
emacs -> init.el : load files with require
init.el -> "core-modules.el" : core-load-modules
init.el -> emacs : message finish
@enduml
