# Docker Compose
# https://docs.docker.com/compose/

version: '3'
services:

  # App service.
  app:
    image: emacs.d/dev/app
    environment: &environment
      - ENVIRONMENT=local
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    volumes:
    - ./:/home/.emacs.d
    env_file:
      - .env

  docs:
    restart: always
    image: emacs.d/dev/docs
    build:
      context: .
      dockerfile: provision/docker/docs/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
    depends_on:
      - app
