# Docker Compose
# https://docs.docker.com/compose/

version: '3.6'
services:
  # Python
  app:
    environment: &environment
      - ENVIRONMENT=local
    image: emacs.d-app-dev
    build:
      args:
        stage: dev
    env_file:
      - .env

  check:
    image: emacs.d-check-dev
    environment: *environment
    build:
      context: .
      dockerfile: provision/docker/check/Dockerfile
      args:
        stage: dev
    env_file:
      - .env

  docs:
    image: emacs.d-docs-dev
    build:
      context: .
      dockerfile: provision/docker/docs/Dockerfile
    env_file:
      - .env
    depends_on:
      - app
